from setuptools import setup

setup(
    name='DrewBerraSample',
    version='',
    packages=['venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.click',
              'venv.lib.python3.6.site-packages.flask', 'venv.lib.python3.6.site-packages.flask.json',
              'venv.lib.python3.6.site-packages.jinja2', 'venv.lib.python3.6.site-packages.jsonify',
              'venv.lib.python3.6.site-packages.werkzeug', 'venv.lib.python3.6.site-packages.werkzeug.debug',
              'venv.lib.python3.6.site-packages.werkzeug.contrib', 'venv.lib.python3.6.site-packages.aniso8601',
              'venv.lib.python3.6.site-packages.markupsafe', 'venv.lib.python3.6.site-packages.sqlalchemy',
              'venv.lib.python3.6.site-packages.sqlalchemy.ext',
              'venv.lib.python3.6.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.6.site-packages.sqlalchemy.orm', 'venv.lib.python3.6.site-packages.sqlalchemy.sql',
              'venv.lib.python3.6.site-packages.sqlalchemy.util', 'venv.lib.python3.6.site-packages.sqlalchemy.event',
              'venv.lib.python3.6.site-packages.sqlalchemy.engine',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.6.site-packages.sqlalchemy.databases',
              'venv.lib.python3.6.site-packages.sqlalchemy.connectors', 'venv.lib.python3.6.site-packages.itsdangerous',
              'venv.lib.python3.6.site-packages.flask_restful', 'venv.lib.python3.6.site-packages.flask_restful.utils',
              'venv.lib.python3.6.site-packages.flask_restful.representations',
              'venv.lib.python3.6.site-packages.flask_sqlalchemy',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='drewberra',
    author_email='',
    description=''
)
